name: torrent-stack

services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun  # Enables VPN tunneling inside the container
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Disables IPv6 to prevent leaks

    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}  # Private key for authentication (from .env)
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - PORT_FORWARD_ONLY="on"
      - VPN_PORT_FORWARDING="on"
      - TZ=${TZ}  # Sets the timezone for correct timestamps in logs
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_NETWORK}  # Allows LAN access through the VPN

    volumes:
      - gluetun-config:/gluetun

    ports:
      - ${GLUETUN_CONTROL_PORT:-8000}:8000  # Gluetun Control server
      - "${TSMN_WEBUI_PORT:-9091}:9091"     # Transmission Web UI

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    network_mode: "service:gluetun"  # Forces Transmission to use Gluetun's network stack

    depends_on:
      gluetun:
        condition: service_healthy  # Ensures Transmission starts only when the VPN is fully functional

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${AUTH_USER}
      - PASS=${AUTH_PASS}

    volumes:
      - ${DOWNLOADS_DIR}:/downloads
      - transmission-config:/config
      - ./transmission-settings.sh:/custom-cont-init.d/transmission-settings.sh:ro

    # Adjusts file descriptor limits for better performance with many torrents
    # note that this may have to be adjusted based on your host system limits.
    ulimits:
      nofile:
        soft: ${ULIMIT_OFILE_SOFT:-4096}
        hard: ${ULIMIT_OFILE_HARD:-8192}

  transmission-port-update:
    image: ghcr.io/whit-colm/transmission-gluetun-port-update:latest
    network_mode: service:gluetun
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_USERNAME=${AUTH_USER}
      - TRANSMISSION_RPC_PASSWORD=${AUTH_PASS}
    restart: "unless-stopped"

  webdav:
    image: hacdias/webdav:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
      - "${WEBDAV_PORT:-8080}:8080"
    volumes:
      - ${DOWNLOADS_DIR}:/data:ro
      - ./webdav-config.yml:/config.yml:ro
    environment:
      - USERNAME=${AUTH_USER}
      - PASSWORD=${AUTH_PASS}
    command: --config /config.yml

volumes:
  gluetun-config:
  transmission-config:
